verify_signatures: false

PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    problem_on_unmodified_line: warn
    on_warn: fail # Treat all warnings as failures
PrePush:
  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rspec']
